In [1]:
import pandas as pd

In [2]:
file = 'F:\\_Bounty\\942854057_alta-view-hospital_standardcharges\\942854057_alta-view-hospital_standardcharges.xml'

df = pd.read_xml(file)
df

,Author,LastAuthor,TotalTime,Created,LastSaved,Version,AllowPNG,Colors,WindowHeight,WindowWidth,WindowTopX,WindowTopY,ProtectStructure,ProtectWindows,Style,Name,Table,WorksheetOptions
0,Ferah Syed,Patrick Mitchell,0.0,2023-03-24T14:40:44Z,2023-03-27T14:32:57Z,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
1,None,None,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
2,None,None,NaN,None,None,NaN,NaN,NaN,15840.0,29040.0,32767.0,32767.0,False,False,NaN,None,NaN,NaN
3,None,None,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
4,None,None,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard Charge Rates,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,None,None,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UMR United Healthcare ions PPO,NaN,NaN
81,None,None,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UMR United Medical Resions PPO,NaN,NaN
82,None,None,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Health Care _ Hrrington,NaN,NaN
83,None,None,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Healthcare,NaN,NaN
84,None,None,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USHealth Group FreedomLife UHC,NaN,NaN