In [8]:
import pandas as pd
import datetime as dt

df = pd.read_json('F:\\_Bounty\\581954432_northsidehospitalatlanta_standardcharges.json', encoding='UTF-16')

In [13]:
df.rename(columns={
    "prices posted and effective": "file_last_updated",
    "code description": "code_desc",
    "payer": "plan_name",
}, inplace=True)

In [11]:
df["file_last_updated"] = pd.to_datetime(df["file_last_updated"])

In [14]:
df

,name,file_last_updated,code,code_desc,payer,gross charge,discounted cash price,payer-specific negotiated charge,de-identified minimum negotiated charge,de-identified maximum negotiated charge
0,Northside Hospital Atlanta,2022-07-05,0001A,ADM SARSCOV2 30MCG/0.3ML 1ST,AETNA HMO,48,12,0.003719,0.000715,0.009693
1,Northside Hospital Atlanta,2022-07-05,0002A,ADM SARSCOV2 30MCG/0.3ML 2ND,AETNA HMO,0.008713137,0.002178284,0.003930,0.000309,0.007654
2,Northside Hospital Atlanta,2022-07-05,0202U,NFCT DS 22 TRGT SARS-COV-2,AETNA HMO,1546.983178,386.7457944,418.433575,42.051203,1414.257850
3,Northside Hospital Atlanta,2022-07-05,10030,GUIDE CATHET FLUID DRAINAGE,AETNA HMO,709,177.25,626.504981,58.547550,692.000308
4,Northside Hospital Atlanta,2022-07-05,19000,DRAINAGE OF BREAST LESION,AETNA HMO,886.32,221.58,869.486053,166.043417,883.705897
...,...,...,...,...,...,...,...,...,...,...
37006,Northside Hospital Atlanta,2022-07-05,172,NEWBORN - LEVEL II UB04 REVENUE CODE,UHC PPO,4216.772754,1054.193189,2261.999348,1261.473840,3199.999000
37007,Northside Hospital Atlanta,2022-07-05,173,NEWBORN - LEVEL III UB04 REVENUE CODE,UHC PPO,5757.174465,1439.293616,3175.880482,1774.718538,4369.121778
37008,Northside Hospital Atlanta,2022-07-05,174,NEWBORN - LEVEL IV UB04 REVENUE CODE,UHC PPO,7866.254899,1966.563725,3353.932799,1237.460072,5990.985000
37009,Northside Hospital Atlanta,2022-07-05,200,INTENSIVE CARE,UHC PPO,5310.91269,1327.728173,3238.561764,182.118680,4374.741326
37010,Northside Hospital Atlanta,2022-07-05,206,INTENSIVE CARE - INTERMEDIATE ICU,UHC PPO,4730.524255,1182.631064,1633.558203,1316.469344,3975.476077